In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.CSV")

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [4]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [5]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [6]:
dependent=dataset[['classification_yes']]

In [7]:
#from sklearn.model_selection import train_test_split
#x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
independent= sc.fit_transform(independent)
#x_test_= sc.transform(x_test)

In [9]:
import pickle
xfilename="svc_model.pkl"
pickle.dump(sc,open("svc_model.pkl",'wb'))
sc=pickle.load(open("svc_model.pkl",'rb'))

In [10]:
from sklearn.svm import SVC

In [11]:
from sklearn.model_selection import GridSearchCV

param_grid = {'kernel':['linear','rbf','poly','sigmoid'],
             'gamma':['auto','scale'],
             'C':[10,50,100,200,300]} 



grid = GridSearchCV(SVC(probability=True), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   

grid.fit(independent,dependent)

Fitting 5 folds for each of 40 candidates, totalling 200 fits


C:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GridSearchCV(estimator=SVC(probability=True), n_jobs=-1,
             param_grid={'C': [10, 50, 100, 200, 300],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['linear', 'rbf', 'poly', 'sigmoid']},
             scoring='f1_weighted', verbose=3)

In [12]:
re=grid.cv_results_
grid_predictions = grid.predict(independent) 
   
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(dependent, grid_predictions)

from sklearn.metrics import classification_report
clf_report = classification_report(dependent, grid_predictions)




In [13]:
from sklearn.metrics import f1_score
f1_macro=f1_score(dependent,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)


The f1_macro value for best parameter {'C': 10, 'gamma': 'auto', 'kernel': 'poly'}: 1.0


In [14]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[150   0]
 [  0 249]]


In [15]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       150
           1       1.00      1.00      1.00       249

    accuracy                           1.00       399
   macro avg       1.00      1.00      1.00       399
weighted avg       1.00      1.00      1.00       399



In [16]:
from sklearn.metrics import roc_auc_score
roc_auc_score(dependent,grid.predict_proba(independent)[:,1])

1.0

In [17]:
table=pd.DataFrame.from_dict(re)

In [22]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0        0.038775      0.018702         0.026184        0.002313      10   
1        0.026183      0.001719         0.028781        0.005265      10   
2        0.048169      0.001164         0.025585        0.002496      10   
3        0.022785      0.001599         0.023785        0.002134      10   
4        0.021785      0.002225         0.023586        0.001356      10   
5        0.024584      0.003497         0.025184        0.002039      10   
6        0.057164      0.010296         0.024385        0.002653      10   
7        0.023786      0.001599         0.023785        0.000748      10   
8        0.019987      0.002190         0.022786        0.000748      50   
9        0.023585      0.003439         0.025185        0.003369      50   
10       0.046970      0.004730         0.024386        0.001199      50   
11       0.020786      0.002133         0.022188        0.001165      50   
12       0.019987      0.001897         0.023585        0.002057      50   
13       0.024986      0.003947         0.024385        0.002415      50   
14       0.044574      0.003876         0.024383        0.001854      50   
15       0.028182      0.008323         0.023785        0.002313      50   
16       0.026783      0.006732         0.024186        0.002783     100   
17       0.026184      0.007621         0.023785        0.001165     100   
18       0.042374      0.003664         0.025185        0.001720     100   
19       0.020588      0.001356         0.023984        0.001094     100   
20       0.027182      0.009614         0.022588        0.001354     100   
21       0.022785      0.003541         0.022787        0.001599     100   
22       0.042572      0.002800         0.023786        0.000748     100   
23       0.023185      0.002225         0.024185        0.000749     100   
24       0.019589      0.001356         0.025184        0.002311     200   
25       0.022985      0.002895         0.025585        0.003553     200   
26       0.042174      0.002992         0.023786        0.001165     200   
27       0.020189      0.001165         0.024585        0.002726     200   
28       0.021386      0.001743         0.023785        0.002038     200   
29       0.025984      0.003576         0.023785        0.001469     200   
30       0.043173      0.001719         0.024785        0.003122     200   
31       0.022786      0.002039         0.023784        0.003654     200   
32       0.020788      0.002315         0.023785        0.000749     300   
33       0.022185      0.003309         0.023386        0.001200     300   
34       0.042172      0.003542         0.025185        0.002225     300   
35       0.021587      0.002415         0.023386        0.000799     300   
36       0.021587      0.003322         0.023586        0.001356     300   
37       0.021586      0.001742         0.024585        0.001624     300   
38       0.042573      0.001019         0.023786        0.001326     300   
39       0.020186      0.001939         0.021588        0.004452     300   

   param_gamma param_kernel  \
0         auto       linear   
1         auto          rbf   
2         auto         poly   
3         auto      sigmoid   
4        scale       linear   
5        scale          rbf   
6        scale         poly   
7        scale      sigmoid   
8         auto       linear   
9         auto          rbf   
10        auto         poly   
11        auto      sigmoid   
12       scale       linear   
13       scale          rbf   
14       scale         poly   
15       scale      sigmoid   
16        auto       linear   
17        auto          rbf   
18        auto         poly   
19        auto      sigmoid   
20       scale       linear   
21       scale          rbf   
22       scale         poly   
23       scale      sigmoid   
24        auto       linear   
25        auto          rbf   
26        auto         poly   
27        auto     

In [23]:
import pickle
filename="final_svc_model.sav"
pickle.dump(grid,open("final_svc_model.sav",'wb'))

In [19]:
preinput=sc.transform([[51,70,0,0,219,36,1.3,139,3.7,12.5,49,6600,4.705,0,0,1,1,0,1,1,0,1,0,0,1,1,0]])

C:\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [20]:
preinput

array([[-2.90035181e-02, -4.79397659e-01, -6.85199355e-01,
        -3.80814665e-01,  9.48067301e-01, -4.35970806e-01,
        -3.16440999e-01,  1.59843796e-01, -3.28835132e-01,
        -6.69369132e-03,  1.24353032e+00, -7.16672489e-01,
        -7.10773454e-04, -5.04694939e-01, -5.16397779e-01,
         2.07846097e+00,  7.48331477e+00, -2.73666982e+00,
         4.85071250e-01,  2.91547595e+00, -2.41568702e-01,
         1.31638775e+00, -7.19103794e-01, -3.05205971e-01,
         5.12501930e-01,  2.04494943e+00, -4.20703162e-01]])

In [21]:
Future_Prediction=grid.predict(preinput) 
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]


In [24]:
loaded_model=pickle.load(open("final_svc_model.sav",'rb'))
result=loaded_model.predict(preinput)


In [25]:
result

array([1])