In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.CSV")

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [4]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [5]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [6]:
dependent=dataset[['classification_yes']]

In [7]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import GridSearchCV

param_grid = {'priors':[None],
             'var_smoothing':[1e-09]}

grid = GridSearchCV(GaussianNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 

grid.fit(independent, dependent) 

re=grid.cv_results_
grid_predictions = grid.predict(independent) 
   
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(dependent, grid_predictions)

from sklearn.metrics import classification_report
clf_report = classification_report(dependent, grid_predictions)

from sklearn.metrics import f1_score
f1_macro=f1_score(dependent,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

print("The confusion Matrix:\n",cm)
print("The report:\n",clf_report)


Fitting 5 folds for each of 1 candidates, totalling 5 fits
The f1_macro value for best parameter {'priors': None, 'var_smoothing': 1e-09}: 0.9874927342358296
The confusion Matrix:
 [[149   1]
 [  4 245]]
The report:
               precision    recall  f1-score   support

           0       0.97      0.99      0.98       150
           1       1.00      0.98      0.99       249

    accuracy                           0.99       399
   macro avg       0.98      0.99      0.99       399
weighted avg       0.99      0.99      0.99       399



C:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [8]:
from sklearn.metrics import roc_auc_score
roc_auc_score(dependent,grid.predict_proba(independent)[:,1])


0.996532797858099

In [9]:
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_priors  \
0       0.064974      0.016998         0.053579        0.012284         None   

  param_var_smoothing                                    params  \
0                 0.0  {'priors': None, 'var_smoothing': 1e-09}   

   split0_test_score  split1_test_score  split2_test_score  split3_test_score  \
0           0.962813           0.987539           0.987539                1.0   

   split4_test_score  mean_test_score  std_test_score  rank_test_score  
0           0.974684         0.982515        0.012694                1

In [10]:
from sklearn.naive_bayes import CategoricalNB
from sklearn.model_selection import GridSearchCV
param_grid = {'alpha':[1.0],
              'force_alpha':[True,False],
              'fit_prior':[True,False]}
grid = GridSearchCV(CategoricalNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
grid.fit(independent,dependent) 



Fitting 5 folds for each of 4 candidates, totalling 20 fits


C:\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:976: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan]
  warnings.warn(
C:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GridSearchCV(estimator=CategoricalNB(), n_jobs=-1,
             param_grid={'alpha': [1.0], 'fit_prior': [True, False],
                         'force_alpha': [True, False]},
             scoring='f1_weighted', verbose=3)

In [11]:
re=grid.cv_results_
grid_predictions = grid.predict(independent) 
   
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(dependent, grid_predictions)

from sklearn.metrics import classification_report
clf_report = classification_report(dependent, grid_predictions)

from sklearn.metrics import f1_score
f1_macro=f1_score(dependent,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

print("The confusion Matrix:\n",cm)
print("The report:\n",clf_report)


The f1_macro value for best parameter {'alpha': 1.0, 'fit_prior': True, 'force_alpha': True}: 0.9974953761738116
The confusion Matrix:
 [[150   0]
 [  1 248]]
The report:
               precision    recall  f1-score   support

           0       0.99      1.00      1.00       150
           1       1.00      1.00      1.00       249

    accuracy                           1.00       399
   macro avg       1.00      1.00      1.00       399
weighted avg       1.00      1.00      1.00       399



In [12]:
from sklearn.metrics import roc_auc_score
roc_auc_score(dependent,grid.predict_proba(independent)[:,1])


0.9999196787148594

In [13]:
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_alpha  \
0       0.074770      0.012459         0.409038        0.268625         1.0   
1       0.297482      0.346895         0.271892        0.334132         1.0   
2       0.200520      0.197732         0.184927        0.118314         1.0   
3       0.120152      0.071479         0.155538        0.101684         1.0   

  param_fit_prior param_force_alpha  \
0            True              True   
1            True             False   
2           False              True   
3           False             False   

                                              params  split0_test_score  \
0  {'alpha': 1.0, 'fit_prior': True, 'force_alpha...           0.950296   
1  {'alpha': 1.0, 'fit_prior': True, 'force_alpha...           0.950296   
2  {'alpha': 1.0, 'fit_prior': False, 'force_alph...           0.950296   
3  {'alpha': 1.0, 'fit_prior': False, 'force_alph...           0.950296   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                NaN                NaN                NaN                NaN   
1                NaN                NaN                NaN                NaN   
2                NaN                NaN                NaN                NaN   
3                NaN                NaN                NaN                NaN   

   mean_test_score  std_test_score  rank_test_score  
0              NaN             NaN                1  
1              NaN             NaN                1  
2              NaN             NaN                1  
3              NaN             NaN                1

In [14]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import GridSearchCV
param_grid = {'alpha':[1.0],
              'force_alpha':[True,False],
              'fit_prior':[True,False]}
grid = GridSearchCV(MultinomialNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
grid.fit(independent,dependent)

re=grid.cv_results_
grid_predictions = grid.predict(independent) 
   
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(dependent, grid_predictions)

from sklearn.metrics import classification_report
clf_report = classification_report(dependent, grid_predictions)

from sklearn.metrics import f1_score
f1_macro=f1_score(dependent,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

print("The confusion Matrix:\n",cm)
print("The report:\n",clf_report)




Fitting 5 folds for each of 4 candidates, totalling 20 fits
The f1_macro value for best parameter {'alpha': 1.0, 'fit_prior': True, 'force_alpha': True}: 0.8544422491701906
The confusion Matrix:
 [[145   5]
 [ 54 195]]
The report:
               precision    recall  f1-score   support

           0       0.73      0.97      0.83       150
           1       0.97      0.78      0.87       249

    accuracy                           0.85       399
   macro avg       0.85      0.87      0.85       399
weighted avg       0.88      0.85      0.85       399



C:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [15]:
from sklearn.metrics import roc_auc_score
roc_auc_score(dependent,grid.predict_proba(independent)[:,1])

0.9499866131191431

In [16]:
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_alpha  \
0       0.332869      0.149890         0.036385        0.002798         1.0   
1       0.187725      0.094210         0.026989        0.005998         1.0   
2       0.133947      0.106636         0.025392        0.001744         1.0   
3       0.101960      0.059849         0.025589        0.003719         1.0   

  param_fit_prior param_force_alpha  \
0            True              True   
1            True             False   
2           False              True   
3           False             False   

                                              params  split0_test_score  \
0  {'alpha': 1.0, 'fit_prior': True, 'force_alpha...           0.658856   
1  {'alpha': 1.0, 'fit_prior': True, 'force_alpha...           0.658856   
2  {'alpha': 1.0, 'fit_prior': False, 'force_alph...           0.658856   
3  {'alpha': 1.0, 'fit_prior': False, 'force_alph...           0.658856   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.864654           0.913563           0.913778           0.924484   
1           0.864654           0.913563           0.913778           0.924484   
2           0.864654           0.901354           0.901535           0.924484   
3           0.864654           0.901354           0.901535           0.924484   

   mean_test_score  std_test_score  rank_test_score  
0         0.855067        0.100278                1  
1         0.855067        0.100278                1  
2         0.850177        0.097562                3  
3         0.850177        0.097562                3

In [17]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import GridSearchCV

param_grid = {'alpha':[1.0],
              'force_alpha':[True,False],
              'fit_prior':[True,False],
              'binarize':[0.5]}


grid = GridSearchCV(BernoulliNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
grid.fit(independent,dependent)

re=grid.cv_results_
grid_predictions = grid.predict(independent) 
   
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(dependent, grid_predictions)

from sklearn.metrics import classification_report
clf_report = classification_report(dependent, grid_predictions)

from sklearn.metrics import f1_score
f1_macro=f1_score(dependent,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

print("The confusion Matrix:\n",cm)
print("The report:\n",clf_report)




Fitting 5 folds for each of 4 candidates, totalling 20 fits
The f1_macro value for best parameter {'alpha': 1.0, 'binarize': 0.5, 'fit_prior': True, 'force_alpha': True}: 0.9503534780347094
The confusion Matrix:
 [[149   1]
 [ 19 230]]
The report:
               precision    recall  f1-score   support

           0       0.89      0.99      0.94       150
           1       1.00      0.92      0.96       249

    accuracy                           0.95       399
   macro avg       0.94      0.96      0.95       399
weighted avg       0.95      0.95      0.95       399



C:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [18]:
from sklearn.metrics import roc_auc_score
roc_auc_score(dependent,grid.predict_proba(independent)[:,1])

0.9948862115127175

In [19]:
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_alpha  \
0       0.072372      0.060891         0.048780        0.014408         1.0   
1       0.122152      0.072638         0.032986        0.010766         1.0   
2       0.103159      0.091771         0.029988        0.005327         1.0   
3       0.128348      0.048021         0.025790        0.002638         1.0   

  param_binarize param_fit_prior param_force_alpha  \
0            0.5            True              True   
1            0.5            True             False   
2            0.5           False              True   
3            0.5           False             False   

                                              params  split0_test_score  \
0  {'alpha': 1.0, 'binarize': 0.5, 'fit_prior': T...           0.913778   
1  {'alpha': 1.0, 'binarize': 0.5, 'fit_prior': T...           0.913778   
2  {'alpha': 1.0, 'binarize': 0.5, 'fit_prior': F...           0.889274   
3  {'alpha': 1.0, 'binarize': 0.5, 'fit_prior': F...           0.889274   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.938259           0.975148           0.950521           0.974684   
1           0.938259           0.975148           0.950521           0.974684   
2           0.938259           0.975148           0.950521           0.974684   
3           0.938259           0.975148           0.950521           0.974684   

   mean_test_score  std_test_score  rank_test_score  
0         0.950478        0.023198                1  
1         0.950478        0.023198                1  
2         0.945577        0.031527                3  
3         0.945577        0.031527                3

In [20]:
from sklearn.naive_bayes import ComplementNB 
from sklearn.model_selection import GridSearchCV

param_grid = {'alpha':[1.0],
              'force_alpha':[True,False],
              'fit_prior':[True,False],
              'norm':[True,False]}


grid = GridSearchCV(ComplementNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
grid.fit(independent,dependent)

re=grid.cv_results_
grid_predictions = grid.predict(independent) 
   
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(dependent, grid_predictions)

from sklearn.metrics import classification_report
clf_report = classification_report(dependent, grid_predictions)

from sklearn.metrics import f1_score
f1_macro=f1_score(dependent,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

print("The confusion Matrix:\n",cm)
print("The report:\n",clf_report)





Fitting 5 folds for each of 8 candidates, totalling 40 fits
The f1_macro value for best parameter {'alpha': 1.0, 'fit_prior': True, 'force_alpha': True, 'norm': False}: 0.8495031532827364
The confusion Matrix:
 [[145   5]
 [ 56 193]]
The report:
               precision    recall  f1-score   support

           0       0.72      0.97      0.83       150
           1       0.97      0.78      0.86       249

    accuracy                           0.85       399
   macro avg       0.85      0.87      0.84       399
weighted avg       0.88      0.85      0.85       399



C:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [21]:
from sklearn.metrics import roc_auc_score
roc_auc_score(dependent,grid.predict_proba(independent)[:,1])

0.9499866131191431

In [22]:
table=pd.DataFrame.from_dict(re)

In [23]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_alpha  \
0       0.071571      0.070492         0.055178        0.016283         1.0   
1       0.100163      0.136908         0.029985        0.004941         1.0   
2       0.294283      0.161046         0.024590        0.001019         1.0   
3       0.117954      0.050683         0.025589        0.002332         1.0   
4       0.049384      0.048799         0.026986        0.002448         1.0   
5       0.181329      0.114478         0.031986        0.011380         1.0   
6       0.192323      0.035435         0.024190        0.000748         1.0   
7       0.081569      0.066199         0.032986        0.008805         1.0   

  param_fit_prior param_force_alpha param_norm  \
0            True              True       True   
1            True              True      False   
2            True             False       True   
3            True             False      False   
4           False              True       True   
5           False              True      False   
6           False             False       True   
7           False             False      False   

                                              params  split0_test_score  \
0  {'alpha': 1.0, 'fit_prior': True, 'force_alpha...           0.204545   
1  {'alpha': 1.0, 'fit_prior': True, 'force_alpha...           0.658856   
2  {'alpha': 1.0, 'fit_prior': True, 'force_alpha...           0.204545   
3  {'alpha': 1.0, 'fit_prior': True, 'force_alpha...           0.658856   
4  {'alpha': 1.0, 'fit_prior': False, 'force_alph...           0.204545   
5  {'alpha': 1.0, 'fit_prior': False, 'force_alph...           0.658856   
6  {'alpha': 1.0, 'fit_prior': False, 'force_alph...           0.204545   
7  {'alpha': 1.0, 'fit_prior': False, 'force_alph...           0.658856   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.204545           0.204545           0.204545           0.209035   
1           0.864654           0.901354           0.901535           0.924484   
2           0.204545           0.204545           0.204545           0.209035   
3           0.864654           0.901354           0.901535           0.924484   
4           0.204545           0.204545           0.204545           0.209035   
5           0.864654           0.901354           0.901535           0.924484   
6           0.204545           0.204545           0.204545           0.209035   
7           0.864654           0.901354           0.901535           0.924484   

   mean_test_score  std_test_score  rank_test_score  
0         0.205443        0.001796                5  
1         0.850177        0.097562                1  
2         0.205443        0.001796                5  
3         0.850177        0.097562                1  
4         0.205443        0.001796                5  
5         0.850177        0.097562                1  
6         0.205443        0.001796                5  
7         0.850177        0.097562                1

In [24]:
Future_Prediction=grid.predict(preinput) 
print("Future_Prediction={}".format(Future_Prediction))

NameError: name 'preinput' is not defined